import {getMachines,saveMachine,getMachineParts,saveMachinePart} from '../../services/machines.service.js';
import {getPartNumbers} from '../../services/master-data.service.js';
const canManage=i=>['administrator','manager'].includes(i.role);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function dialog(html,title,onSave){const d=document.createElement('div');d.className='user-dialog-backdrop';d.innerHTML=`<div class="user-dialog"><div class="user-dialog-header"><div><p class="eyebrow">Machine Management</p><h2>${title}</h2></div><button class="dialog-close">×</button></div>${html}</div>`;d.onclick=e=>{if(e.target===d)d.remove()};d.querySelector('.dialog-close').onclick=()=>d.remove();d.querySelector('[data-close]').onclick=()=>d.remove();d.querySelector('form').onsubmit=async e=>{e.preventDefault();await onSave(new FormData(e.currentTarget));d.remove();document.dispatchEvent(new Event('machines-refresh'))};document.body.append(d)}
function machineForm(m={}){return `<form class="master-form"><input type="hidden" name="id" value="${m.id||''}"><label>Machine Code<input name="machine_code" required maxlength="80" value="${esc(m.machine_code||'')}"></label><label>Machine Name<input name="machine_name" required maxlength="160" value="${esc(m.machine_name||'')}"></label><label>Machine Type<input name="machine_type" maxlength="100" value="${esc(m.machine_type||'')}"></label><label>Status<select name="status"><option value="active" ${m.status!=='inactive'?'selected':''}>Active</option><option value="inactive" ${m.status==='inactive'?'selected':''}>Inactive</option></select></label><div class="form-actions"><button type="button" class="secondary-button" data-close>Cancel</button><button class="primary-button">Save machine</button></div></form>`}
function relationForm(r={},parts=[]){return `<form class="master-form"><input type="hidden" name="id" value="${r.id||''}"><label>Part Number<select name="part_number_id" required><option value="">Select part number</option>${parts.filter(p=>p.status==='active'||p.id===r.part_number_id).map(p=>`<option value="${p.id}" ${p.id===r.part_number_id?'selected':''}>${esc(p.part_number)} — ${esc(p.description||'')}</option>`).join('')}</select></label><label>Standard Cycle Time (seconds)<input name="standard_cycle_time_seconds" type="number" min="0.001" step="0.001" required value="${r.standard_cycle_time_seconds??''}"></label><label>Status<select name="status"><option value="active" ${r.status!=='inactive'?'selected':''}>Active</option><option value="inactive" ${r.status==='inactive'?'selected':''}>Inactive</option></select></label><div class="form-actions"><button type="button" class="secondary-button" data-close>Cancel</button><button class="primary-button">Save relationship</button></div></form>`}
export async function renderMachinesModule(el,{company,identity}){let rows=await getMachines(),parts=await getPartNumbers();const manage=canManage(identity);let selected=null;
async function render(){el.innerHTML=`<div class="master-module"><div class="module-heading"><div><p class="eyebrow">Machine Management</p><h1>Machines</h1><p class="muted">Configure production equipment and approved part numbers.</p></div>${manage?'<button class="primary-button" id="add-machine">Add machine</button>':''}</div><div class="users-toolbar"><input id="search-machine" placeholder="Search machine code, name or type"><select id="filter-machine"><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></div><div class="users-table-wrap"><table class="users-table"><thead><tr><th>Code</th><th>Name</th><th>Type</th><th>Status</th><th>Action</th></tr></thead><tbody id="machine-rows"></tbody></table></div><div id="relationship-panel"></div></div>`;
const paint=()=>{let q=el.querySelector('#search-machine').value.toLowerCase(),f=el.querySelector('#filter-machine').value;let list=rows.filter(m=>(!q||`${m.machine_code} ${m.machine_name} ${m.machine_type||''}`.toLowerCase().includes(q))&&(f==='all'||m.status===f));el.querySelector('#machine-rows').innerHTML=list.map(m=>`<tr><td><strong>${esc(m.machine_code)}</strong></td><td>${esc(m.machine_name)}</td><td>${esc(m.machine_type||'—')}</td><td><span class="status status-${m.status}">${m.status}</span></td><td><button class="table-action action-enabled" data-open="${m.id}">Part Numbers</button>${manage?` <button class="table-action action-enabled" data-edit="${m.id}">Manage</button>`:''}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No machines found.</td></tr>';el.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{selected=rows.find(m=>m.id===b.dataset.open);showRelations()});el.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openMachine(rows.find(m=>m.id===b.dataset.edit)))};
el.querySelector('#search-machine').oninput=paint;el.querySelector('#filter-machine').onchange=paint;paint();if(manage)el.querySelector('#add-machine').onclick=()=>openMachine();if(selected)showRelations()}
async function showRelations(){if(!selected)return;let rel=await getMachineParts(selected.id);const panel=el.querySelector('#relationship-panel');panel.innerHTML=`<div class="module-heading" style="margin-top:28px"><div><p class="eyebrow">Machine ↔ Part Number</p><h2>${esc(selected.machine_code)} — ${esc(selected.machine_name)}</h2><p class="muted">Cycle time is stored in seconds.</p></div>${manage&&selected.status==='active'?'<button class="primary-button" id="add-relation">Assign part number</button>':''}</div><div class="users-table-wrap"><table class="users-table"><thead><tr><th>Part Number</th><th>Customer</th><th>Cycle Time</th><th>Status</th><th>Action</th></tr></thead><tbody>${rel.map(r=>`<tr><td><strong>${esc(r.part_numbers?.part_number||'—')}</strong><br><small>${esc(r.part_numbers?.description||'')}</small></td><td>${esc(r.part_numbers?.customers?.name||'—')}</td><td>${Number(r.standard_cycle_time_seconds)} sec</td><td><span class="status status-${r.status}">${r.status}</span></td><td>${manage?`<button class="table-action action-enabled" data-rel="${r.id}">Manage</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No part numbers assigned.</td></tr>'}</tbody></table></div>`;if(manage)panel.querySelector('#add-relation')?.addEventListener('click',()=>openRelation());panel.querySelectorAll('[data-rel]').forEach(b=>b.onclick=()=>openRelation(rel.find(r=>r.id===b.dataset.rel)))}
function openMachine(m={}){dialog(machineForm(m),m.id?'Manage machine':'Add machine',async fd=>{let p={machine_code:fd.get('machine_code').trim(),machine_name:fd.get('machine_name').trim(),machine_type:fd.get('machine_type').trim()||null,status:fd.get('status')};if(!fd.get('id'))p.company_id=company.id;await saveMachine(p,fd.get('id')||null);rows=await getMachines();await render()})}
function openRelation(r={}){let existing=selected?null:null;dialog(relationForm(r,parts),r.id?'Manage relationship':'Assign part number',async fd=>{let p={machine_id:selected.id,part_number_id:fd.get('part_number_id'),standard_cycle_time_seconds:Number(fd.get('standard_cycle_time_seconds')),status:fd.get('status')};if(!fd.get('id'))p.company_id=company.id;await saveMachinePart(p,fd.get('id')||null);await showRelations()})}
await render()}
