-- First create the user in Supabase Authentication, then run:
-- select public.bootstrap_company('Metrics Works','METRICS','metricsworks','PUT-USER-UUID-HERE','Company Administrator','America/Monterrey');
