import {getMachines} from "../../services/machines.service.js";
import {getCompanyShifts} from "../../services/shifts.service.js";
import {getProductionRecords,getProductionParts,createProductionRecord} from "../../services/production.service.js";
const canCapture=i=>["administrator","manager","supervisor"].includes(i.role);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
export async function renderProductionModule(el,{company,identity}){
  const capture=canCapture(identity); let machines,shifts,records;
  try { [machines,shifts,records]=await Promise.all([getMachines(),getCompanyShifts(company.id),getProductionRecords()]); } catch (err) { console.error(err); el.innerHTML=`<div class="master-module"><div class="module-heading"><div><p class="eyebrow">Production Capture</p><h1>Production</h1><p class="muted">Unable to load production data.</p><p class="error">${esc(err.message||"Unknown error")}</p></div></div></div>`; return; }
  machines=machines.filter(x=>x.status==="active"); shifts=shifts.filter(x=>x.is_active===true);
  const today=new Date().toISOString().slice(0,10);
  el.innerHTML=`<div class="master-module"><div class="module-heading"><div><p class="eyebrow">Production Capture</p><h1>Production</h1><p class="muted">Record completed production by shift, machine and part number.</p></div></div>
  ${capture?`<form id="production-form" class="master-form production-form"><div class="form-grid"><label>Production Date<input type="date" name="production_date" value="${today}" required></label><label>Shift<select name="shift_id" required><option value="">Select shift</option>${shifts.map(s=>`<option value="${s.id}">${esc(s.name||s.code||"Shift")}</option>`).join("")}</select></label><label>Machine<select name="machine_id" id="production-machine" required><option value="">Select machine</option>${machines.map(m=>`<option value="${m.id}">${esc(m.machine_code)} — ${esc(m.machine_name)}</option>`).join("")}</select></label><label>Part Number<select name="part_number_id" id="production-part" required disabled><option value="">Select machine first</option></select></label><label>Quantity Produced<input name="quantity_produced" type="number" min="0.001" step="0.001" required></label><label>Notes<input name="notes" maxlength="500" placeholder="Optional"></label></div><div class="form-actions"><button class="primary-button">Save Production</button><span id="production-message" class="muted"></span></div></form>`:`<p class="muted">Your role has view-only access to production records.</p>`}
  <div class="users-table-wrap" style="margin-top:24px"><table class="users-table"><thead><tr><th>Date</th><th>Shift</th><th>Machine</th><th>Part Number</th><th>Quantity</th><th>Captured</th></tr></thead><tbody id="production-rows"></tbody></table></div></div>`;
  const paint=()=>el.querySelector('#production-rows').innerHTML=records.map(r=>`<tr><td>${esc(r.production_date)}</td><td>${esc(r.company_shifts?.name||r.company_shifts?.code||"—")}</td><td><strong>${esc(r.machines?.machine_code||"—")}</strong><br><small>${esc(r.machines?.machine_name||"")}</small></td><td><strong>${esc(r.part_numbers?.part_number||"—")}</strong><br><small>${esc(r.part_numbers?.description||"")}</small></td><td>${Number(r.quantity_produced ?? 0).toLocaleString()}</td><td>${new Date(r.created_at).toLocaleString()}</td></tr>`).join("")||'<tr><td colspan="6" class="empty">No production records yet.</td></tr>';
  paint();
  if(!capture)return;
  const machineSel=el.querySelector('#production-machine'), partSel=el.querySelector('#production-part'), msg=el.querySelector('#production-message');
  machineSel.onchange=async()=>{try{partSel.disabled=true;partSel.innerHTML='<option>Loading...</option>';const parts=await getProductionParts(machineSel.value);partSel.innerHTML='<option value="">Select part number</option>'+parts.map(x=>`<option value="${x.part_number_id}">${esc(x.part_numbers.part_number)}${x.part_numbers.description?' — '+esc(x.part_numbers.description):''}</option>`).join('');partSel.disabled=false;}catch(e){console.error(e);partSel.innerHTML='<option value="">Unable to load part numbers</option>';}};
  el.querySelector('#production-form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const btn=e.currentTarget.querySelector('.primary-button');try{btn.disabled=true;msg.textContent='Saving...';await createProductionRecord({company_id:company.id,production_date:fd.get('production_date'),shift_id:fd.get('shift_id'),machine_id:fd.get('machine_id'),part_number_id:fd.get('part_number_id'),quantity_produced:Number(fd.get('quantity_produced')),notes:fd.get('notes').trim()||null,created_by:identity.user_id});msg.textContent='Production saved successfully.';e.currentTarget.reset();e.currentTarget.production_date.value=today;partSel.innerHTML='<option value="">Select machine first</option>';partSel.disabled=true;records=await getProductionRecords();paint();}catch(err){console.error(err);msg.textContent=err.message||'Unable to save production.';}finally{btn.disabled=false;}};
}
